### ISSUE TITLE
Whitelist Spring MVC RestController 

### ISSUE THREAD

**Issue by balatbn** [calrissian/rest-doclet#12]
Current SpringCollector checks only for @Controller annotation. Can you please add @RestController as part of CONTROLLER_ANNOTATION?

**Comment by balatbn** [comment]
Created a pull request for the same.

https://github.com/calrissian/rest-doclet/pull/13

**Comment by eawagner** [comment]
Sorry, for not getting on this sooner.  Your pull request has been merged.
